name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o mdefaults ./cmd/mdefaults

    - name: Run E2E Tests
      run: |
        go run ./test/e2e/run_tests.go --verbose
